/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import ui.pages.PagesController;
import service.BookShelfService;

/**
 *
 * @author marth
 */
public class AppFrame extends javax.swing.JFrame {
    
    private BookShelfService bookShelfService;
    /**
     * Creates new form AppFrame
     */
    public AppFrame() {
        initComponents();
        
        jPanel2.removeAll();
        jPanel2.add(PagesController.greeting);

        repaint();
        revalidate();
        
    }

    public void setBookShelfService( BookShelfService bookShelfService) {
        this.bookShelfService = bookShelfService;
    }
            
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        btnMyBook = new javax.swing.JButton();
        btnAbout = new javax.swing.JButton();
        btnArchived = new javax.swing.JButton();
        btnGreating = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(181, 101, 29));

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/bookshelf.png"))); // NOI18N
        jLabel1.setText("My Book Shelf Aplication");

        jButton2.setBackground(new java.awt.Color(181, 101, 29));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/homepage.png"))); // NOI18N
        jButton2.setText("Home");
        jButton2.setBorderPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnMyBook.setBackground(new java.awt.Color(181, 101, 29));
        btnMyBook.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMyBook.setForeground(new java.awt.Color(255, 255, 255));
        btnMyBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/mybookpage.png"))); // NOI18N
        btnMyBook.setText("My Books");
        btnMyBook.setBorderPainted(false);
        btnMyBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMyBookActionPerformed(evt);
            }
        });

        btnAbout.setBackground(new java.awt.Color(181, 101, 29));
        btnAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/about.png"))); // NOI18N
        btnAbout.setBorderPainted(false);
        btnAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAboutActionPerformed(evt);
            }
        });

        btnArchived.setBackground(new java.awt.Color(181, 101, 29));
        btnArchived.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnArchived.setForeground(new java.awt.Color(255, 255, 255));
        btnArchived.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/archievedpage.png"))); // NOI18N
        btnArchived.setText("My Archieved");
        btnArchived.setBorderPainted(false);
        btnArchived.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArchivedActionPerformed(evt);
            }
        });

        btnGreating.setBackground(new java.awt.Color(181, 101, 29));
        btnGreating.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/wave.png"))); // NOI18N
        btnGreating.setBorderPainted(false);
        btnGreating.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGreatingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnGreating, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(77, 77, 77)
                .addComponent(btnMyBook, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(btnArchived)
                .addGap(53, 53, 53)
                .addComponent(btnAbout)
                .addGap(41, 41, 41))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2)
                            .addComponent(btnMyBook)
                            .addComponent(btnArchived)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnAbout))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnGreating, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jPanel2.removeAll();
        jPanel2.add(PagesController.homePage);

        repaint();
        revalidate();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnMyBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMyBookActionPerformed
        
        PagesController.myBookPage.setBookShelfService(bookShelfService);
        PagesController.myBookPage.setTable();
       
      
        jPanel2.removeAll();
        jPanel2.add(PagesController.myBookPage);
       
        repaint();
        revalidate();
        bookShelfService.showBook(null);
    }//GEN-LAST:event_btnMyBookActionPerformed

    private void btnArchivedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArchivedActionPerformed
        
        PagesController.archievedPage.setBookShelfService(bookShelfService);
        PagesController.archievedPage.setTable();
        
        jPanel2.removeAll();
        jPanel2.add(PagesController.archievedPage);

        repaint();
        revalidate();
        bookShelfService.showBook2(null);
    }//GEN-LAST:event_btnArchivedActionPerformed

    private void btnAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAboutActionPerformed
        jPanel2.removeAll();
        jPanel2.add(PagesController.aboutPage);
        
        repaint();
        revalidate();
    }//GEN-LAST:event_btnAboutActionPerformed

    private void btnGreatingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGreatingActionPerformed
        jPanel2.removeAll();
        jPanel2.add(PagesController.greeting);

        repaint();
        revalidate();
    }//GEN-LAST:event_btnGreatingActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbout;
    private javax.swing.JButton btnArchived;
    private javax.swing.JButton btnGreating;
    private javax.swing.JButton btnMyBook;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
