/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.pages;

import java.util.ArrayList;
import javax.swing.JTable;
import entity.MyBookShelf;
import service.BookShelfService;

/**
 *
 * @author marth
 */
public class ArchievedPage extends javax.swing.JPanel {
    private BookShelfService bookShelfService;

    /**
     * Creates new form ArchievedPage
     */
    public ArchievedPage() {
        initComponents();
    }
    
    public JTable getTable (){
        
        return tblArchieved;
    } 
    
    
     public void setTable() {
        bookShelfService.setTableBook2(tblArchieved);
        bookShelfService.showBook2(null);
    }
    public void setBookShelfService(BookShelfService bookShelfService) {
        this.bookShelfService = bookShelfService;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblArchieved = new javax.swing.JTable();

        setBackground(new java.awt.Color(181, 101, 29));

        jPanel1.setBackground(new java.awt.Color(181, 101, 29));

        jLabel1.setFont(new java.awt.Font("Lucida Calligraphy", 1, 23)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Archieved Page");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Untitled design (2).png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        tblArchieved.setAutoCreateRowSorter(true);
        tblArchieved.setBackground(new java.awt.Color(249, 247, 244));
        tblArchieved.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ISBN", "Title", "Author", "Publisher", "Year", "Total Pages", "Action"
            }
        ));
        tblArchieved.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblArchievedMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblArchieved);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 886, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblArchievedMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblArchievedMouseReleased
        int row = tblArchieved.rowAtPoint(evt.getPoint());
        int col = tblArchieved.columnAtPoint(evt.getPoint());
        
        if (row >= 0 && col == 0) {
            int selectedIsbn = (int) tblArchieved.getValueAt(row, 0);
            MyBookShelf myBookShelf = bookShelfService.getByIsbn(selectedIsbn);

            DetailBook detailFrame = new DetailBook();
            detailFrame.setMyBook(myBookShelf);
            detailFrame.setBookShelfService(bookShelfService);
            if (detailFrame.isVisible() == true) {
                detailFrame.dispose();
            } else {
                detailFrame.setVisible(true);
            }
        }
    }//GEN-LAST:event_tblArchievedMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblArchieved;
    // End of variables declaration//GEN-END:variables
}
